dist: bionic
sudo: required
language: csharp
mono: none
dotnet: 2.2.105
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_install:
  # install Neo4j locally:
  - apt-get install neo4j=1:3.5.4
  - service neo4j start
  
install:
  - dotnet restore src/AutoInc.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/servicestack

script:
  - dotnet build src/AutoInc.sln
  - dotnet test src/AutoInc.Neo4j.Tests/AutoInc.Neo4j.Tests.csproj
